bin_PROGRAMS = sparsefs
AM_CPPFLAGS = -I$(srcdir)
sparsefs_SOURCES = sparsefs.c wildmatch.c
EXTRA_DIST = wildmatch.h tests/test.sh \
	tests/test1/src1/both12 \
	tests/test1/src1/path1/source1 \
	tests/test1/src1/path12/both12 \
	tests/test1/src1/path12/source1 \
	tests/test1/src1/source1 \
	tests/test1/src2/both12 \
	tests/test1/src2/path12/both12 \
	tests/test1/src2/path12/source2 \
	tests/test1/src2/path2/source2 \
	tests/test1/src2/source2
